services:
  - type: web
    name: imst-book
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn iMst_Book.wsgi:application"
    autoDeploy: true
   